Ext.define('Newcasetrack1.newcasetrack1.shared.com.model.lexmauriscontext.legal.CaseDetailModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "caseDetId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "dateOfHearing",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "nextDateOfHearing",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "listOfOrders",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});