Ext.define('Newcasetrack1.newcasetrack1.shared.com.model.lexmauriscontext.legal.CaseInformationModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "caseId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "caseNo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "forumid",
          "reference": "Forum",
          "defaultValue": ""
     }, {
          "name": "casetypeid",
          "reference": "CaseType",
          "defaultValue": ""
     }, {
          "name": "caseYear",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "casestatusid",
          "reference": "CaseStatus",
          "defaultValue": ""
     }, {
          "name": "caseTitle",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "filingDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "judgementDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "diaryNo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "judgement",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});