Ext.define('Newcasetrack1.newcasetrack1.shared.com.model.lexmauriscontext.legal.JudgeRegistrationModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "judgeRegId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "jcontactid",
          "reference": "CoreContacts",
          "defaultValue": ""
     }, {
          "name": "barId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "forumid",
          "reference": "Forum",
          "defaultValue": ""
     }, {
          "name": "appointmentDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "dateOfRetirement",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "fStartDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "fEndDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "caseCount",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});