DROP TABLE IF EXISTS `ast_JudgeRegistration_T`;

CREATE TABLE `ast_JudgeRegistration_T` ( `judgeRegId` VARCHAR(256) NOT NULL, `jContactId` VARCHAR(64) NOT NULL, `barId` VARCHAR(256) NULL DEFAULT NULL, `forumId` VARCHAR(256) NOT NULL, `appointmentDate` DATETIME NOT NULL, `dateOfRetirement` DATETIME NULL DEFAULT NULL, `fStartDate` DATETIME NULL DEFAULT NULL, `fEndDate` DATETIME NULL DEFAULT NULL, `caseCount` INT(10) NULL DEFAULT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` DATETIME NULL DEFAULT '1900-01-01', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` DATETIME NULL DEFAULT '1900-01-01', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`judgeRegId`));

