DROP TABLE IF EXISTS `ast_CaseInterveener_T`;

CREATE TABLE `ast_CaseInterveener_T` ( `caseIntId` VARCHAR(256) NOT NULL, `caseId` VARCHAR(256) NOT NULL, `advocateId` VARCHAR(256) NOT NULL, `startDate` DATETIME NOT NULL, `endDate` DATETIME NULL DEFAULT NULL, `advCatId` VARCHAR(256) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` DATETIME NULL DEFAULT '1900-01-01', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` DATETIME NULL DEFAULT '1900-01-01', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`caseIntId`));

