Ext.define('Newcasetrack1.newcasetrack1.shared.com.model.lexmauriscontext.userprofile.ProfileLitSubCategoryModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "litProfileId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "litcatid",
          "reference": "LitigationCategory",
          "defaultValue": ""
     }, {
          "name": "litsubcatid",
          "reference": "LitigationSubCategory",
          "defaultValue": ""
     }, {
          "name": "regid",
          "reference": "SignUp",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});