Ext.define('Newcasetrack1.newcasetrack1.shared.com.model.lexmauriscontext.userprofile.UserSignupRegModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "registrationId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "contactId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "titleId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "firstName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "lastName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "genderId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "timeZoneId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "phoneNumber",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "emailId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "userTypeId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bar",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "dateofbirth",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "UserSignupPwd",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "usrSignup",
          "type": "auto",
          "defaultValue": ""
     }]
});